### ISSUE TITLE
Images are trimmed a little too aggressively

### ISSUE THREAD

**Issue by pento** [markus-wa/stickerify#1]
This is a super neat little package, thanks for making it available! 🙂

Whilst testing it out, I noticed a bug where it seems like the trim is a little too aggressive, taking an extra row of pixels from the right/bottom. The behaviour becomes very noticeable when running stickerify twice on the same image.

Here's a demo where you can see the bug in action: https://codepen.io/pento/pen/NWvYpRe

**Comment by markus-wa** [comment]
Hi @pento - thanks for raising this!

Very cool idea actually to call it twice with a thick white outline followed by 1px black!

With just a quick look I couldn't spot the bug, so I'll try to delve into it a bit deeper soon (otherwise if you find what it is, PRs are very welcome :smile:)

**Comment by markus-wa** [comment]
I will actually include a link to a codepen example based on yours as I think that shows the usage really well. Hope you don't mind :smile: (will credit you in the readme of course!)

**Comment by pento** [comment]
Go for it, I hope folks find it useful! 🙂
