### ISSUE TITLE
Suggestion: Provide a Promise-based interface

### ISSUE THREAD

**Issue by pento** [markus-wa/stickerify#4]
While working with Stickerify, I've found that I frequently want to perform multiple operations on the image, it gets super verbose to be making `Image` objects every step of the way. I've been using a small Promise wrapper to fix this:

```js
const promiseStickerify = ( imgSrc, size, color ) => {
	return new Promise( ( resolve, reject ) => {
		const image = new Image();
		image.onload = () => resolve( stickerify( image, size, color ) );
		image.onerror = ( e ) => reject( e );
		image.src = imgSrc;
	} );
};
```

It can then be used like so:

```js
const paddedImage = await stickerify( imgURL, 15, 'white' )
	.then( ( img ) => stickerify( img.toDataURL(), 3, 'grey' ) );
```

This is a bit of a departure from how the library currently works, so I didn't want to open a PR without discussing it first. 🙂

**Comment by markus-wa** [comment]
great suggestion - maybe there is a way to avoid using `HTMLImageElement` altogether, but I'm not sure (tbh I'm not a frontend dev and not familiar with JS image APIs).

It would be good to decouple the whole thing from DOM elements - there should be a core API that can be used for both Browser & Node.js and then there should be extended APIs that wrap the core API making it easy to use from both frontend and backend. hope that makes sense.

Anyway, I'd be happy to look at and review any PR for this - I think it would be a great addition!
